# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-15 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tombApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='critter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Critter name', max_length=40)),
                ('hp', models.IntegerField(default=1, help_text='Hit Points')),
                ('ac', models.IntegerField(default=10, help_text='Armor Class')),
                ('dam', models.IntegerField(default=5, help_text='Damage Done')),
                ('hitbon', models.IntegerField(default=6, help_text='Damage Done')),
            ],
        ),
    ]
